In [41]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1] # 모든 행중, 마지막 열을 뺀 모든 값, 즉 X의 값
y_data = xy[:, [-1]] # 모든 행중, 마지막 열에 해당 되는 값, 즉 Y의 값

# print(x_data.shape, x_data, len(x_data)) # shape = 배열의 크기, len(x_data) = 행 개수
# print(y_data.shape, y_data)

X = tf.placeholder(tf.float32, shape=[None, 3]) # 3개 값
Y = tf.placeholder(tf.float32, shape=[None, 1]) # Final 값

W = tf.Variable(tf.random_normal([3, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]),name='bias')

#Hypothesis
hypothesis = tf.matmul(X, W) + b

# cost
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session() # graph 그리기

# 그래프 그리기 전 값 초기화
sess.run(tf.global_variables_initializer())

#Set up feed_dict variables inside the Loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X:x_data, Y: y_data}
    )
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# 점수 예측 하기, 나중에 최종 점수(y)는 몇이나 올까?
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X:[[60,70,110], [90,100,80]]}))



0 Cost:  114477.6 
Prediction:
 [[-161.99094 ]
 [-198.50685 ]
 [-193.51599 ]
 [-211.38448 ]
 [-151.95622 ]
 [-113.71918 ]
 [-158.3061  ]
 [-117.291245]
 [-187.31369 ]
 [-175.41664 ]
 [-153.01079 ]
 [-152.88168 ]
 [-199.27477 ]
 [-165.04692 ]
 [-159.69502 ]
 [-201.71931 ]
 [-157.60368 ]
 [-189.37662 ]
 [-189.29411 ]
 [-169.13863 ]
 [-185.84973 ]
 [-186.68379 ]
 [-176.69319 ]
 [-161.8245  ]
 [-204.76534 ]]
10 Cost:  26.464573 
Prediction:
 [[153.89426]
 [181.18208]
 [180.58463]
 [196.04767]
 [137.61768]
 [ 99.7873 ]
 [146.67654]
 [108.81126]
 [167.54826]
 [153.2921 ]
 [140.82298]
 [136.85838]
 [187.21494]
 [156.22908]
 [146.694  ]
 [183.58124]
 [148.36703]
 [176.63196]
 [179.16351]
 [160.54204]
 [171.79138]
 [169.52182]
 [164.28506]
 [156.64458]
 [188.73071]]
20 Cost:  20.870657 
Prediction:
 [[156.06151]
 [183.81036]
 [183.16153]
 [198.86261]
 [139.62097]
 [101.2801 ]
 [148.7897 ]
 [110.38561]
 [170.02039]
 [155.60278]
 [142.85715]
 [138.87772]
 [189.86894]
 [158.42474]
 [148.82132]
 [1

330 Cost:  17.337418 
Prediction:
 [[155.6365 ]
 [183.97339]
 [182.95473]
 [198.88359]
 [139.7096 ]
 [101.80404]
 [148.98244]
 [110.75608]
 [170.62987]
 [156.77176]
 [142.99086]
 [139.40129]
 [189.41502]
 [157.74059]
 [149.14284]
 [186.5921 ]
 [149.71364]
 [179.39857]
 [181.11311]
 [162.2572 ]
 [174.50488]
 [172.34444]
 [166.74045]
 [157.81981]
 [191.39412]]
340 Cost:  17.238728 
Prediction:
 [[155.62334]
 [183.97769]
 [182.94795]
 [198.88365]
 [139.71178]
 [101.81941]
 [148.98784]
 [110.76699]
 [170.6476 ]
 [156.80637]
 [142.99446]
 [139.41655]
 [189.40082]
 [157.71956]
 [149.15208]
 [186.60165]
 [149.69084]
 [179.40509]
 [181.09529]
 [162.24043]
 [174.51147]
 [172.35442]
 [166.74292]
 [157.78961]
 [191.39192]]
350 Cost:  17.140936 
Prediction:
 [[155.61021 ]
 [183.98196 ]
 [182.94125 ]
 [198.8837  ]
 [139.71393 ]
 [101.83471 ]
 [148.99323 ]
 [110.777855]
 [170.66522 ]
 [156.84079 ]
 [142.99805 ]
 [139.43176 ]
 [189.38667 ]
 [157.6986  ]
 [149.16132 ]
 [186.61118 ]
 [149.66814 ]
 [179

720 Cost:  14.065808 
Prediction:
 [[155.16551 ]
 [184.12552 ]
 [182.71265 ]
 [198.88635 ]
 [139.78429 ]
 [102.35395 ]
 [149.17906 ]
 [111.152626]
 [171.26408 ]
 [158.01222 ]
 [143.1208  ]
 [139.94847 ]
 [188.90479 ]
 [156.98372 ]
 [149.47713 ]
 [186.934   ]
 [148.8922  ]
 [179.63641 ]
 [180.4737  ]
 [161.65569 ]
 [174.7438  ]
 [172.70122 ]
 [166.8314  ]
 [156.73651 ]
 [191.31352 ]]
730 Cost:  13.99579 
Prediction:
 [[155.15451]
 [184.12904]
 [182.70699]
 [198.88643]
 [139.78595]
 [102.36679]
 [149.18373]
 [111.16205]
 [171.27888]
 [158.04124]
 [143.12387]
 [139.96127]
 [188.8928 ]
 [156.96594]
 [149.48502]
 [186.942  ]
 [148.87285]
 [179.6421 ]
 [180.45871]
 [161.64162]
 [174.74947]
 [172.70955]
 [166.8336 ]
 [156.71112]
 [191.31158]]
740 Cost:  13.926391 
Prediction:
 [[155.14357]
 [184.13252]
 [182.70134]
 [198.88652]
 [139.7876 ]
 [102.37957]
 [149.1884 ]
 [111.17144]
 [171.29362]
 [158.07016]
 [143.1269 ]
 [139.974  ]
 [188.88089]
 [156.94823]
 [149.49287]
 [186.94994]
 [148.85359

1090 Cost:  11.844802 
Prediction:
 [[154.79117]
 [184.2438 ]
 [182.5188 ]
 [198.88974]
 [139.83865]
 [102.79132]
 [149.3411 ]
 [111.47895]
 [171.76843]
 [159.00429]
 [143.22598]
 [140.38512]
 [188.49486]
 [156.37434]
 [149.7485 ]
 [187.206  ]
 [148.22769]
 [179.83473]
 [179.96127]
 [161.1746 ]
 [174.93909]
 [172.98518]
 [166.90828]
 [155.86884]
 [191.24586]]
1100 Cost:  11.794223 
Prediction:
 [[154.7819  ]
 [184.24667 ]
 [182.514   ]
 [198.88983 ]
 [139.83992 ]
 [102.802124]
 [149.34517 ]
 [111.48715 ]
 [171.78091 ]
 [159.02887 ]
 [143.2286  ]
 [140.39592 ]
 [188.48468 ]
 [156.35918 ]
 [149.75528 ]
 [187.2127  ]
 [148.2111  ]
 [179.83975 ]
 [179.94856 ]
 [161.16269 ]
 [174.944   ]
 [172.99219 ]
 [166.91025 ]
 [155.8473  ]
 [191.24414 ]]
1110 Cost:  11.744079 
Prediction:
 [[154.7727 ]
 [184.24956]
 [182.50922]
 [198.88994]
 [139.84119]
 [102.81288]
 [149.34924]
 [111.49534]
 [171.79333]
 [159.05334]
 [143.23123]
 [140.4067 ]
 [188.47452]
 [156.34409]
 [149.76204]
 [187.21939]
 [148.1

1320 Cost:  10.78677 
Prediction:
 [[154.58904]
 [184.30643]
 [182.41347]
 [198.89214]
 [139.8657 ]
 [103.02758]
 [149.43126]
 [111.66032]
 [172.04091]
 [159.5428 ]
 [143.28366]
 [140.6217 ]
 [188.27147]
 [156.04167]
 [149.89767]
 [187.35294]
 [147.86346]
 [179.94614]
 [179.68263]
 [160.91347]
 [175.04704]
 [173.13869]
 [166.95192]
 [155.39723]
 [191.20763]]
1330 Cost:  10.745448 
Prediction:
 [[154.58075]
 [184.30899]
 [182.40913]
 [198.89224]
 [139.86676]
 [103.0373 ]
 [149.43501]
 [111.66787]
 [172.05212]
 [159.56497]
 [143.28604]
 [140.63144]
 [188.26227]
 [156.02795]
 [149.90385]
 [187.35898]
 [147.84842]
 [179.9508 ]
 [179.67116]
 [160.90273]
 [175.05154]
 [173.145  ]
 [166.95374]
 [155.3778 ]
 [191.20605]]
1340 Cost:  10.704458 
Prediction:
 [[154.57248]
 [184.31152]
 [182.40482]
 [198.89233]
 [139.86783]
 [103.04695]
 [149.43875]
 [111.67537]
 [172.06326]
 [159.58707]
 [143.28842]
 [140.64111]
 [188.25308]
 [156.01427]
 [149.90999]
 [187.36499]
 [147.83342]
 [179.95541]
 [179.6

1580 Cost:  9.821486 
Prediction:
 [[154.3853 ]
 [184.3685 ]
 [182.3067 ]
 [198.89502]
 [139.89093]
 [103.26586]
 [149.52446]
 [111.84763]
 [172.31569]
 [160.08813]
 [143.34256]
 [140.86087]
 [188.04453]
 [155.70317]
 [150.05034]
 [187.50116]
 [147.49161]
 [180.06218]
 [179.40005]
 [160.64902]
 [175.15804]
 [173.29361]
 [166.99774]
 [154.91913]
 [191.16763]]
1590 Cost:  9.788586 
Prediction:
 [[154.37796]
 [184.37071]
 [182.30283]
 [198.89514]
 [139.89182]
 [103.27446]
 [149.52788]
 [111.85449]
 [172.32562]
 [160.10786]
 [143.3447 ]
 [140.86952]
 [188.03632]
 [155.6909 ]
 [150.05591]
 [187.5065 ]
 [147.4781 ]
 [180.06644]
 [179.38983]
 [160.63947]
 [175.16208]
 [173.2992 ]
 [166.99944]
 [154.90182]
 [191.16617]]
1600 Cost:  9.755951 
Prediction:
 [[154.37064]
 [184.37292]
 [182.29898]
 [198.89525]
 [139.89267]
 [103.28301]
 [149.53128]
 [111.86131]
 [172.33548]
 [160.1275 ]
 [143.34683]
 [140.87813]
 [188.02812]
 [155.67865]
 [150.06143]
 [187.51181]
 [147.46465]
 [180.07071]
 [179.379

1930 Cost:  8.824826 
Prediction:
 [[154.14757]
 [184.43929]
 [182.18118]
 [198.89915]
 [139.91727]
 [103.5441 ]
 [149.63684]
 [112.07323]
 [172.63655]
 [160.72841]
 [143.41248]
 [141.1411 ]
 [187.77693]
 [155.30324]
 [150.23207]
 [187.67426]
 [147.05035]
 [180.20345]
 [179.06764]
 [160.33853]
 [175.29094]
 [173.47462]
 [167.05408]
 [154.35703]
 [191.1187 ]]
1940 Cost:  8.800591 
Prediction:
 [[154.14134 ]
 [184.44112 ]
 [182.17787 ]
 [198.89928 ]
 [139.91791 ]
 [103.551384]
 [149.63985 ]
 [112.07926 ]
 [172.64497 ]
 [160.74525 ]
 [143.41434 ]
 [141.14847 ]
 [187.76988 ]
 [155.29268 ]
 [150.2369  ]
 [187.67879 ]
 [147.03867 ]
 [180.20726 ]
 [179.05888 ]
 [160.33037 ]
 [175.29448 ]
 [173.47939 ]
 [167.0556  ]
 [154.34221 ]
 [191.11739 ]]
1950 Cost:  8.776558 
Prediction:
 [[154.13513]
 [184.44293]
 [182.17459]
 [198.89938]
 [139.91853]
 [103.55866]
 [149.64285]
 [112.08528]
 [172.65334]
 [160.76202]
 [143.41617]
 [141.15579]
 [187.76283]
 [155.28215]
 [150.2417 ]
 [187.68332]
 [147.0270

In [42]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(
['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# 각 각 필드의 데이터타입은 0., 0. (float32)이다.
record_defaults =  [[0.], [0.], [0.],[0.]]
# csv를 decord 한다. 이를 xy로 읽어온다.
xy = tf.decode_csv(value, record_defaults=record_defaults)


train_x_batch, train_y_batch = \
  tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10) # 한번의 펌프당 10개씩
  # xy[0:-1] - x_data, xy[-1:] - y_data, batch_size=한번에 가져올 값.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name="weight") # 위 x값과 맞춰야함.
b = tf.Variable(tf.random_normal([1]), name="bias") # Y 값과 맞춰야함.

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))    
  
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
    
sess = tf.Session()
sess.run(tf.global_variables_initializer())


#Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X:x_batch, Y:y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  9758.451 
Prediction:
 [[57.47592 ]
 [69.58829 ]
 [68.25741 ]
 [74.60668 ]
 [53.032722]
 [39.685043]
 [56.189796]
 [42.09571 ]
 [65.54004 ]
 [61.42244 ]]
10 Cost:  5.303566 
Prediction:
 [[153.2092  ]
 [184.67403 ]
 [181.64069 ]
 [198.09729 ]
 [140.80385 ]
 [104.409546]
 [148.63162 ]
 [110.63247 ]
 [173.1105  ]
 [161.07771 ]]
20 Cost:  5.478314 
Prediction:
 [[153.85167 ]
 [185.45094 ]
 [182.40346 ]
 [198.9318  ]
 [141.39441 ]
 [104.851364]
 [149.26062 ]
 [111.10469 ]
 [173.84235 ]
 [161.76442 ]]
30 Cost:  5.469922 
Prediction:
 [[153.85243]
 [185.45645]
 [182.4062 ]
 [198.93857]
 [141.39664]
 [104.85936]
 [149.27   ]
 [111.11757]
 [173.85316]
 [161.78319]]
40 Cost:  5.4574323 
Prediction:
 [[153.8489 ]
 [185.45677]
 [182.40388]
 [198.93977]
 [141.39491]
 [104.86441]
 [149.27522]
 [111.12732]
 [173.85912]
 [161.7974 ]]
50 Cost:  5.445032 
Prediction:
 [[153.84538]
 [185.45703]
 [182.4015 ]
 [198.94093]
 [141.39314]
 [104.86941]
 [149.28038]
 [111.13702]
 [173.86497]
 [161.8115

560 Cost:  4.957854 
Prediction:
 [[153.69014 ]
 [185.46243 ]
 [182.29384 ]
 [198.99544 ]
 [141.3031  ]
 [105.09025 ]
 [149.52261 ]
 [111.592575]
 [174.12428 ]
 [162.44841 ]]
570 Cost:  4.9507303 
Prediction:
 [[153.68755]
 [185.46239]
 [182.29198]
 [198.99644]
 [141.30135]
 [105.09397]
 [149.527  ]
 [111.60078]
 [174.12866]
 [162.4594 ]]
580 Cost:  4.943617 
Prediction:
 [[153.68495 ]
 [185.46234 ]
 [182.2901  ]
 [198.9974  ]
 [141.29958 ]
 [105.097664]
 [149.53133 ]
 [111.60898 ]
 [174.133   ]
 [162.47034 ]]
590 Cost:  4.9366217 
Prediction:
 [[153.68239]
 [185.4623 ]
 [182.28825]
 [198.99838]
 [141.29782]
 [105.10135]
 [149.53566]
 [111.61714]
 [174.13731]
 [162.48123]]
600 Cost:  4.9297094 
Prediction:
 [[153.67986]
 [185.46225]
 [182.28642]
 [198.99937]
 [141.29607]
 [105.105  ]
 [149.54   ]
 [111.62528]
 [174.14162]
 [162.49208]]
610 Cost:  4.922851 
Prediction:
 [[153.67732]
 [185.46219]
 [182.28458]
 [199.00034]
 [141.29431]
 [105.10864]
 [149.5443 ]
 [111.63339]
 [174.14587]
 

1090 Cost:  4.6684065 
Prediction:
 [[153.5724 ]
 [185.45439]
 [182.20538]
 [199.04349]
 [141.21083]
 [105.26037]
 [149.73569]
 [111.99428]
 [174.32404]
 [162.96436]]
1100 Cost:  4.664429 
Prediction:
 [[153.57054 ]
 [185.45415 ]
 [182.20392 ]
 [199.04433 ]
 [141.20914 ]
 [105.263084]
 [149.7394  ]
 [112.00123 ]
 [174.32724 ]
 [162.97289 ]]
1110 Cost:  4.66049 
Prediction:
 [[153.5687  ]
 [185.45389 ]
 [182.20245 ]
 [199.04517 ]
 [141.20743 ]
 [105.265785]
 [149.74307 ]
 [112.00816 ]
 [174.33043 ]
 [162.98138 ]]
1120 Cost:  4.656583 
Prediction:
 [[153.56685 ]
 [185.45363 ]
 [182.20097 ]
 [199.04597 ]
 [141.2057  ]
 [105.26848 ]
 [149.74672 ]
 [112.015076]
 [174.33357 ]
 [162.9898  ]]
1130 Cost:  4.6527452 
Prediction:
 [[153.56503]
 [185.45337]
 [182.19952]
 [199.04681]
 [141.204  ]
 [105.27116]
 [149.75037]
 [112.02197]
 [174.33673]
 [162.99821]]
1140 Cost:  4.648937 
Prediction:
 [[153.5632 ]
 [185.45311]
 [182.19807]
 [199.04762]
 [141.20229]
 [105.27383]
 [149.75401]
 [112.02885]


1590 Cost:  4.5165377 
Prediction:
 [[153.49251]
 [185.43816]
 [182.13927]
 [199.08208]
 [141.12685]
 [105.37816]
 [149.90651]
 [112.31703]
 [174.46239]
 [163.34396]]
1600 Cost:  4.5143313 
Prediction:
 [[153.49118 ]
 [185.43777 ]
 [182.13808 ]
 [199.0828  ]
 [141.12521 ]
 [105.380165]
 [149.90967 ]
 [112.323006]
 [174.46472 ]
 [163.35066 ]]
1610 Cost:  4.5121503 
Prediction:
 [[153.48982]
 [185.43736]
 [182.1369 ]
 [199.08351]
 [141.12357]
 [105.38216]
 [149.9128 ]
 [112.32894]
 [174.46706]
 [163.35732]]
1620 Cost:  4.5099983 
Prediction:
 [[153.48853]
 [185.43698]
 [182.13574]
 [199.0842 ]
 [141.12193]
 [105.38414]
 [149.91594]
 [112.33487]
 [174.46939]
 [163.36395]]
1630 Cost:  4.5078864 
Prediction:
 [[153.48721 ]
 [185.4366  ]
 [182.13458 ]
 [199.08493 ]
 [141.1203  ]
 [105.3861  ]
 [149.91907 ]
 [112.340775]
 [174.47171 ]
 [163.37056 ]]
1640 Cost:  4.505814 
Prediction:
 [[153.48592]
 [185.4362 ]
 [182.13344]
 [199.08565]
 [141.11867]
 [105.38806]
 [149.9222 ]
 [112.34666]
 [174.