In [2]:
import tensorflow as tf

x_data = [ # n개
    [73.,80.,75.],
    [93.,88.,93.],
    [89.,91.,90.],
    [96.,98.,100.],
    [73.,66.,70.]
]

y_data = [ #n개
    [152.],
    [185.],
    [180.],
    [196.],
    [142.]
]

# Matrix N*N로 , 5*5 나눠짐. 행렬의 곱으로는 앞, 뒤 값이 같아야함.

X = tf.placeholder(tf.float32, shape=[None, 3]) # 예측 3개 행 값
Y = tf.placeholder(tf.float32, shape=[None, 1]) # N개 예측, 1개 행 값

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

#Hypothesis, H(X) = XW
hypothesis = tf.matmul(X, W) + b

#cost
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#minimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch graph
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X:x_data, Y:y_data}
    )
    if step % 10 == 0:
        print(step, "Cost : ", cost_val, "\n Prediction : \n", hy_val)




0 Cost :  58767.4 
 Prediction : 
 [[-60.070736]
 [-75.999695]
 [-72.453285]
 [-83.196465]
 [-55.633045]]
10 Cost :  5.300088 
 Prediction : 
 [[154.36281]
 [181.74533]
 [181.50105]
 [193.35486]
 [140.96329]]
20 Cost :  4.748008 
 Prediction : 
 [[155.0053 ]
 [182.52951]
 [182.26741]
 [194.19087]
 [141.56316]]
30 Cost :  4.734019 
 Prediction : 
 [[155.0009 ]
 [182.53613]
 [182.2677 ]
 [194.19261]
 [141.56996]]
40 Cost :  4.720111 
 Prediction : 
 [[154.9946 ]
 [182.5404 ]
 [182.26569]
 [194.19186]
 [141.57498]]
50 Cost :  4.7062664 
 Prediction : 
 [[154.98828]
 [182.54465]
 [182.26367]
 [194.1911 ]
 [141.57997]]
60 Cost :  4.692526 
 Prediction : 
 [[154.98201]
 [182.54887]
 [182.26164]
 [194.19032]
 [141.58495]]
70 Cost :  4.6788545 
 Prediction : 
 [[154.97572]
 [182.55305]
 [182.25963]
 [194.18956]
 [141.58989]]
80 Cost :  4.665202 
 Prediction : 
 [[154.9695 ]
 [182.55731]
 [182.25763]
 [194.18883]
 [141.59486]]
90 Cost :  4.6516523 
 Prediction : 
 [[154.96324]
 [182.5615 ]
 [18

830 Cost :  3.8148105 
 Prediction : 
 [[154.54358]
 [182.84407]
 [182.12044]
 [194.14131]
 [141.92757]]
840 Cost :  3.8054504 
 Prediction : 
 [[154.53844]
 [182.84752]
 [182.11874]
 [194.1408 ]
 [141.93153]]
850 Cost :  3.7961433 
 Prediction : 
 [[154.53331]
 [182.85098]
 [182.1171 ]
 [194.14029]
 [141.93549]]
860 Cost :  3.7869105 
 Prediction : 
 [[154.5282 ]
 [182.85443]
 [182.11545]
 [194.13976]
 [141.93942]]
870 Cost :  3.7777286 
 Prediction : 
 [[154.52309]
 [182.85783]
 [182.1138 ]
 [194.13924]
 [141.94334]]
880 Cost :  3.768549 
 Prediction : 
 [[154.51799]
 [182.86127]
 [182.11217]
 [194.13875]
 [141.94725]]
890 Cost :  3.759421 
 Prediction : 
 [[154.51292]
 [182.86469]
 [182.1105 ]
 [194.13824]
 [141.95116]]
900 Cost :  3.7503734 
 Prediction : 
 [[154.50784]
 [182.86807]
 [182.10886]
 [194.1377 ]
 [141.95503]]
910 Cost :  3.7413516 
 Prediction : 
 [[154.50282]
 [182.87148]
 [182.10722]
 [194.13722]
 [141.95894]]
920 Cost :  3.7323425 
 Prediction : 
 [[154.49776]
 [182

1650 Cost :  3.1806715 
 Prediction : 
 [[154.16252]
 [183.09966]
 [181.99648]
 [194.10715]
 [142.2162 ]]
1660 Cost :  3.174383 
 Prediction : 
 [[154.15837]
 [183.10245]
 [181.99512]
 [194.10684]
 [142.21933]]
1670 Cost :  3.1680808 
 Prediction : 
 [[154.1542 ]
 [183.10526]
 [181.99376]
 [194.10654]
 [142.22241]]
1680 Cost :  3.1618602 
 Prediction : 
 [[154.15004]
 [183.108  ]
 [181.99239]
 [194.10619]
 [142.22548]]
1690 Cost :  3.155627 
 Prediction : 
 [[154.14592]
 [183.1108 ]
 [181.99104]
 [194.10591]
 [142.22856]]
1700 Cost :  3.1494029 
 Prediction : 
 [[154.14177]
 [183.11357]
 [181.98967]
 [194.10559]
 [142.23163]]
1710 Cost :  3.1432695 
 Prediction : 
 [[154.13766]
 [183.11633]
 [181.98834]
 [194.10529]
 [142.23471]]
1720 Cost :  3.1371431 
 Prediction : 
 [[154.13354]
 [183.11906]
 [181.987  ]
 [194.10498]
 [142.23773]]
1730 Cost :  3.1310015 
 Prediction : 
 [[154.12946]
 [183.12184]
 [181.98564]
 [194.10469]
 [142.24078]]
1740 Cost :  3.1249297 
 Prediction : 
 [[154.12