In [5]:
import tensorflow as tf

x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]

y_data = [152., 185., 180., 196., 142.]


x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)


# H(x1,x2,x3) = x1w1 + x2w2 + x3w3 
w1 = tf.Variable(tf.random_normal([1]), name="weight1")
w2 = tf.Variable(tf.random_normal([1]), name="weight2")
w3 = tf.Variable(tf.random_normal([1]), name="weight3")

b = tf.Variable(tf.random_normal([1]), name="bias")

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

#cost
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
# value init
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data}
                                  )
    if step % 10 ==0:
        print(step, "\n Cost:", cost_val, "\n Prediction: \n", hy_val)


0 
 Cost: 57296.113 
 Prediction: 
 [-53.635796 -75.88527  -69.17005  -72.14974  -63.288452]
10 
 Cost: 45.826424 
 Prediction: 
 [158.00302 178.5346  181.49046 200.81487 130.77992]
20 
 Cost: 45.0828 
 Prediction: 
 [158.6193  179.32101 182.24164 201.63446 131.38982]
30 
 Cost: 44.864582 
 Prediction: 
 [158.59714 179.33995 182.2367  201.63065 131.41428]
40 
 Cost: 44.64739 
 Prediction: 
 [158.57314 179.35654 182.22948 201.62437 131.43695]
50 
 Cost: 44.431355 
 Prediction: 
 [158.54916 179.37305 182.22226 201.61807 131.45953]
60 
 Cost: 44.2166 
 Prediction: 
 [158.52528 179.38953 182.21509 201.61182 131.48206]
70 
 Cost: 44.00291 
 Prediction: 
 [158.50148 179.40599 182.20795 201.60558 131.50453]
80 
 Cost: 43.79029 
 Prediction: 
 [158.47772 179.42236 182.20079 201.59933 131.52696]
90 
 Cost: 43.578857 
 Prediction: 
 [158.45404 179.43872 182.19366 201.59311 131.54932]
100 
 Cost: 43.36863 
 Prediction: 
 [158.4304  179.45502 182.18657 201.58693 131.57161]
110 
 Cost: 43.159485 
 

1080 
 Cost: 27.377522 
 Prediction: 
 [156.40541 180.85367 181.57939 201.04439 133.49426]
1090 
 Cost: 27.253696 
 Prediction: 
 [156.38745 180.86609 181.57402 201.03946 133.51143]
1100 
 Cost: 27.130505 
 Prediction: 
 [156.36954 180.87848 181.56866 201.03456 133.52856]
1110 
 Cost: 27.008007 
 Prediction: 
 [156.35168 180.89082 181.56335 201.02966 133.54565]
1120 
 Cost: 26.886087 
 Prediction: 
 [156.33388 180.90315 181.55803 201.02477 133.5627 ]
1130 
 Cost: 26.764868 
 Prediction: 
 [156.3161  180.91542 181.55269 201.01988 133.57968]
1140 
 Cost: 26.644268 
 Prediction: 
 [156.29839 180.92766 181.54741 201.015   133.59663]
1150 
 Cost: 26.524372 
 Prediction: 
 [156.28075 180.93988 181.54214 201.01015 133.61354]
1160 
 Cost: 26.405014 
 Prediction: 
 [156.26312 180.95209 181.53687 201.00531 133.6304 ]
1170 
 Cost: 26.286343 
 Prediction: 
 [156.24554 180.9642  181.53162 201.00046 133.64722]
1180 
 Cost: 26.168365 
 Prediction: 
 [156.22801 180.9763  181.52638 200.99564 133.66397]