In [8]:
import tensorflow as tf
    # Training Data
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

  # Evaluation our model using Test Dataset
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]



X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    #Initialize Tensorflow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],feed_dict={X:x_data, Y: y_data})
        print(step, cost_val, W_val)
    
    # Predict
    print("Prediction : ", sess.run(prediction, feed_dict={X: x_test}))
    
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))
    


0 4.870494 [[-0.43468004 -0.25114402 -0.01033774]
 [ 0.82640326 -1.5204912  -1.102567  ]
 [-1.1487968  -0.29261857  0.2231436 ]]
1 3.1696982 [[-4.8144457e-01 -2.1532346e-01  6.0622767e-04]
 [ 6.3029605e-01 -1.3494542e+00 -1.0774968e+00]
 [-1.3041141e+00 -1.1003430e-01  1.9587661e-01]]
2 2.0210786 [[-0.50628626 -0.18460777 -0.00526774]
 [ 0.54072446 -1.193372   -1.1440073 ]
 [-1.3549153   0.05445752  0.08218589]]
3 1.3755164 [[-0.524377   -0.17578845  0.00400365]
 [ 0.48145506 -1.1239871  -1.154123  ]
 [-1.377896    0.11759119  0.0420329 ]]
4 1.3108201 [[-0.5314969  -0.18488055  0.02021568]
 [ 0.48128965 -1.1417867  -1.136158  ]
 [-1.345385    0.08945268  0.03766049]]
5 1.2906318 [[-0.54213214 -0.18719168  0.03316206]
 [ 0.4610601  -1.1259031  -1.131812  ]
 [-1.3319434   0.0962671   0.01740451]]
6 1.2744261 [[-0.55104434 -0.19263114  0.04751372]
 [ 0.44966808 -1.1252804  -1.1210427 ]
 [-1.3105248   0.08717175  0.00508125]]
7 1.259342 [[-0.56054157 -0.19668898  0.0610688 ]
 [ 0.4343643  

 [-0.37121192 -0.14877333 -0.6982863 ]]
83 0.72287446 [[-1.0113453  -0.4787841   0.7939676 ]
 [-0.25831625 -0.77561134 -0.76272774]
 [-0.36426654 -0.15051475 -0.7034902 ]]
84 0.72029936 [[-1.0157745  -0.4811715   0.8007843 ]
 [-0.2630371  -0.7727977  -0.76082057]
 [-0.3574324  -0.15221556 -0.7086235 ]]
85 0.7177794 [[-1.0201932  -0.48352486  0.8075564 ]
 [-0.26766175 -0.7700363  -0.7589573 ]
 [-0.35070795 -0.15387622 -0.7136873 ]]
86 0.7153131 [[-1.0246018  -0.48584446  0.8142846 ]
 [-0.27219144 -0.76732653 -0.7571374 ]
 [-0.34409186 -0.15549701 -0.7186826 ]]
87 0.71289897 [[-1.0290008  -0.48813066  0.8209697 ]
 [-0.2766271  -0.76466817 -0.7553601 ]
 [-0.33758253 -0.15707852 -0.7236104 ]]
88 0.7105355 [[-1.0333904  -0.49038365  0.82761234]
 [-0.2809701  -0.76206046 -0.7536248 ]
 [-0.3311787  -0.15862094 -0.7284718 ]]
89 0.7082213 [[-1.037771   -0.49260384  0.83421314]
 [-0.2852213  -0.7595032  -0.75193083]
 [-0.32487857 -0.16012497 -0.7332679 ]]
90 0.7059549 [[-1.042143   -0.49479148  

165 0.60763574 [[-1.3537328  -0.5896949   1.2472656 ]
 [-0.4303637  -0.6632765  -0.70301485]
 [-0.04520055 -0.20385748 -0.96921337]]
166 0.606799 [[-1.3576858  -0.5903125   1.2518361 ]
 [-0.4309241  -0.6627374  -0.7029935 ]
 [-0.04304546 -0.20397352 -0.97125244]]
167 0.60596836 [[-1.3616332  -0.59091866  1.2563896 ]
 [-0.4314677  -0.6622071  -0.70298016]
 [-0.04091    -0.20408605 -0.97327536]]
168 0.6051438 [[-1.365575   -0.5915136   1.2609262 ]
 [-0.4319954  -0.661685   -0.7029746 ]
 [-0.03879406 -0.20419489 -0.9752825 ]]
169 0.60432506 [[-1.3695111  -0.59209734  1.2654462 ]
 [-0.43250728 -0.6611711  -0.7029766 ]
 [-0.0366969  -0.20430046 -0.97727406]]
170 0.6035123 [[-1.3734417  -0.59267014  1.2699496 ]
 [-0.43300396 -0.660665   -0.702986  ]
 [-0.03461828 -0.20440273 -0.9792504 ]]
171 0.6027051 [[-1.3773667  -0.59323215  1.2744366 ]
 [-0.43348578 -0.6601666  -0.7030025 ]
 [-0.03255765 -0.20450203 -0.9812117 ]]
172 0.60190356 [[-1.381286   -0.5937835   1.2789073 ]
 [-0.4339532  -0.659